### PR TITLE
Create DM3BT-DSF-PEJS.kicad_mod

### PR DESCRIPTION
**Pull request by savenlid**
micro sd
push-push
reverse

### CODE REVIEW

**Comment by evanshultz** [comment]
@SchrodingersGat @jkriege2 @poeschlr Could someone close and re-open this PR to trigger Travis?

Datasheet: https://www.hirose.com/product/en/download_file/key_name/DM3BT-DSF-PEJS/category/Drawing%20(2D)/doc_file_id/44097/?file_category_id=6&item_id=06090029900&is_series=

Let's start with the output from KLC script:

> Checking footprint 'DM3BT-DSF-PEJS':
>   Violating Rule 10.3
>     All other properties are left to default values. (Move and Place: Free; Auto Place: 0 and 0,  Local
>     Clearance Values: 0)
>     Attribute solder_mask_margin == 0.1 != 0!
>     Attribute solder_paste_margin == -0.05 != 0!
>   Violating Rule 10.4
>     3D model reference
>     No 3D model provided
>   Violating Rule 7.4
>     Fabrication layer requirements
>     Value Label Errors
>      - Component value is hidden (should be set to visible)
>      - Value label has a height of 0.5mm (expected: 1.0mm)
>      - Value label has a width of 0.5mm (expected: 1.0mm)
>      - Value label has a thickness of 0.1mm (expected: 0.15mm)
>     Some fabrication layer lines have a width outside allowed range of [0.1mm - 0.15mm]
>      - Line (6.05,5.3) -> (6.8,5.1) on layer 'F.Fab' has width '0.05'
>      - Line (6.8,5.6) -> (6.05,5.3) on layer 'F.Fab' has width '0.05'
>      - Line (6.05,5.8) -> (6.8,5.6) on layer 'F.Fab' has width '0.05'
>      - Line (6.8,6.15) -> (6.05,5.8) on layer 'F.Fab' has width '0.05'
>      - Line (6.05,6.5) -> (6.8,6.15) on layer 'F.Fab' has width '0.05'
>      - Line (6.8,6.8) -> (6.05,6.5) on layer 'F.Fab' has width '0.05'
>      - Line (6.05,7.1) -> (6.8,6.8) on layer 'F.Fab' has width '0.05'
>      - Line (6.8,7.45) -> (6.05,7.1) on layer 'F.Fab' has width '0.05'
>      - Line (6.05,7.75) -> (6.8,7.45) on layer 'F.Fab' has width '0.05'
>      - Line (6.8,8.05) -> (6.05,7.75) on layer 'F.Fab' has width '0.05'
>      - Line (6.05,8.35) -> (6.8,8.05) on layer 'F.Fab' has width '0.05'
>      - Line (6.8,8.7) -> (6.05,8.35) on layer 'F.Fab' has width '0.05'
>      - Line (6.8,5.1) -> (6.8,8.7) on layer 'F.Fab' has width '0.05'
>      - Line (6.05,5.1) -> (6.8,5.1) on layer 'F.Fab' has width '0.05'
>      - Line (6.05,8.7) -> (6.05,5.1) on layer 'F.Fab' has width '0.05'
>      - Line (6.8,8.7) -> (6.05,8.7) on layer 'F.Fab' has width '0.05'
>      - Line (6.05,3.5) -> (6.8,3.9) on layer 'F.Fab' has width '0.05'
>      - Line (6.8,3.25) -> (6.05,3.5) on layer 'F.Fab' has width '0.05'
>      - Line (6.05,2.95) -> (6.8,3.25) on layer 'F.Fab' has width '0.05'
>      - Line (6.8,2.75) -> (6.05,2.95) on layer 'F.Fab' has width '0.05'
>      - Line (6.05,2.5) -> (6.8,2.75) on layer 'F.Fab' has width '0.05'
>      - Line (6.8,2.2) -> (6.05,2.5) on layer 'F.Fab' has width '0.05'
>      - Line (6.05,1.9) -> (6.8,2.2) on layer 'F.Fab' has width '0.05'
>      - Line (6.8,1.65) -> (6.05,1.9) on layer 'F.Fab' has width '0.05'
>      - Line (6.05,1.35) -> (6.8,1.65) on layer 'F.Fab' has width '0.05'
>      - Line (6.8,1.35) -> (6.8,3.9) on layer 'F.Fab' has width '0.05'
>      - Line (6.05,1.35) -> (6.8,1.35) on layer 'F.Fab' has width '0.05'
>      - Line (6.05,3.9) -> (6.05,1.35) on layer 'F.Fab' has width '0.05'
>      - Line (6.05,3.9) -> (6.8,3.9) on layer 'F.Fab' has width '0.05'
>   Violating Rule 8.1
>     For surface-mount devices, placement type must be set to "Surface Mount"
>     Surface Mount attribute not set
>      - For SMD footprints, 'Placement type' must be set to 'Surface mount'
>   Violating Rule 9.2
>     For through-hole components, footprint anchor is set on pad 1
>     Pad 1 not located at origin
>      - Set origin to location of Pad 1

**Comment by evanshultz** [comment]
Image:
image

This part has some area which should have a Cu keepout (note 3 in the datasheet). There are lines on the fab layer for this footprint, but that's not very descriptive for KiCad users. Have we found a way to do this in footprints? @SchrodingersGat @jkriege2 @poeschlr 

Other notes:
- Ref des in silk is typically at the top, above the part
- Footprint name should be an F.Fab layer, 1x1mm in size, and placed below the symbol
- The zig zag lines in the fab layer to designate the keepout area might need to change (see above)
- The footprint origin isn't in a place which makes it most easy to check against the datasheet dimensions
- Courtyard is not placed outside the component/footprint extents
- F.Fab line at the top (by pins 1-8) is not orthogonal
- Remove the lines on Eco.User if they're not needed (they appear to be dimensional guide lines)
- What schematic symbol in the library, if any, does this go to? I'd like to check the pin mapping.

@savenlid Will you be able to fix this footprint to meet KLC? I verified all pins look like they're placed correctly, with the exception of pin 11. Instead of further review now, I'd like to address the items noted above and by the Python scripts.

**Comment by evanshultz** [comment]
@savenlid As you've closed https://github.com/KiCad/Connectors_Hirose.pretty/pull/7, does that also mean you'll close this one?

**Comment by savenlid** [comment]
https://github.com/savenlid/kicad

**Pull request closed without merging**
