### PR TITLE
Add Hirose FH26-39S

### PR DESCRIPTION
**Pull request by yaqwsx**
Added a FPC connector Hirose_FH26-39S-0.3SHW (used by ED060SC4 E-ink display). Based on @davidpottingerdesign work, consulted with this datasheet http://www.mouser.com/ds/2/185/FH26_catalog-939414.pdf

### CODE REVIEW

**Comment by davidpottingerdesign** [comment]
Hey, neat.

**Comment by yaqwsx** [comment]
I forgot to add screenshot:
vystrizek

**Comment by pointhi** [comment]
```
checking module: Hirose_FH26-39S-0.3SHW
  Violating Rule 10.5
    Attributes is set to the appropriate value, see tooltip for more information.
  Violating Rule 6.9
    Value and reference have a height of 1mm.
```

Please also note:
- Connectors have a courtjard distance of 0.5mm (see KLC)
- silk screen should be fully visible after assembly

**Comment by yaqwsx** [comment]
I fixed KLC violations and moved the silkscreen a little bit.

3soz_v1

**Review by pointhi — CHANGES_REQUESTED** [review]
- The upper pins shouldn't be so long as the lower ones (only 0.65mm)
- Silk screen should be fully visible after assembly

**Comment by yaqwsx** [comment]
I am not sure, If we are looking at the same version. Both upper and lower pins are 0.3x0.8 mm and the silkscreen is fully visible after assembly.

**Comment by pointhi** [comment]
fh26-39s_review

For the silk screen, it is currently placed in a distance of 13mm on the x-axis. When looking onto the datasheet it says 13.2mm Connector width for your connector, so you have to place the silkscreen on the x-axis at least in a distance of about 13.4-13.5mm to be fully visible. I haven't checked the y axis, but there could be the same problem.

**Comment by yaqwsx** [comment]
My bad, I adjusted the silkscreen position.

k2oz_v1

**Comment by evanshultz** [comment]
@pointhi Since you did the previous review, would you be able to take a look again?

**Comment by poeschlr** [comment]
The upper row of pads (2,4,6,...) still have the wrong y size.

Sadly it seems this PR has been forgotten for quite a while. The problem now is that the [KLC](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) did change quite a bit.

For starters, this footprint is missing the outline, pin 1 marker and reference on the fab layer.

The 3d settings should be filled out as well. 
- Path: ${KISYS3DMOD}/Connectors_Hirose.3dshapes/Hirose_FH26-39S-0.3SHW.wrl
- scale: 1,1,1
- offset: 0,0,0
- rotation: 0,0,0

The documentation field should hold a description of the part not only the link to the datasheet.

Edit: i fixed my 3d path

**Comment by Shackmeister** [comment]
@yaqwsx 
Hi are you planning on picking up on this footprint again? :)

**Comment by yaqwsx** [comment]
I am currently pretty busy and I am not going to update the footprint to match new KLC rules at leas in a month. Feel free to pick it up and update it.

**Comment by poeschlr** [comment]
If you are still interested please recreate this pull request in the new kicad-footprints repo. This repo is now a legacy repo in preparation for the v5 release. Sorry for this inconvenience.

**Pull request closed without merging**
