### PR TITLE
Add Hirose FH12-24S-0.5SH connector footprint

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Datasheet: https://www.hirose.com/product/en/download_file/key_name/FH12%2D24S%2D0.5SH%2855%29/category/Drawing%20(2D)/doc_file_id/75611/?file_category_id=6&item_id=05860521055&is_series=

imagen
imagen

No 3D models. Sorry :P

### CODE REVIEW

**Comment by evanshultz** [comment]
@antoniovazquezblanco 
Thanks for this contribution!

First, are you familiar with the KiCad tools that allow footprint generation by scripting? Instead of making one footprint, all footprints in this family could be generated at once. If you're not interested, that's fine.

A few quick notes:
1. Remove the "o" in silk as the line by pin1 is adequate.
1. Please change `24x0.5mm_Angled` to `1x24_Pitch0.5mm_Horizontal`. We've recently changed the footprint naming and this will conform to the new standard.
1. Please give 0.3mm silk-pad clearance.
1. If the top of the body is at -1.2mm, I calculate the bottom should be at 4.5mm (-1.2 + 2 + 1.2 / 2 - 1.3 + 4.4). Yours is at 4.4mm. Can you please take a look so we're both sure that dimension is right?
image
1. How did you come up with the dimensions for the sections I circled below? Do you have a connector to measure? Guessing based on the datasheet? Some datasheet dimensions I missed?
image

**Comment by antoniovazquezblanco** [comment]
Thanks @evanshultz!

First of all I am not familiar with the scripting footprint generation tools. Can you point me where to look for latest information on that? This time I will solve the footprint issues but I will try to script future contributions.

I am working on your notes. For the 5 one I do not have the connector. It was guessing based on the datasheet (Assuming it was generated with a CAD tool the dimensions are proportional so it can be estimated).

**Comment by antoniovazquezblanco** [comment]
By the way, there was people asking for tasks to improve the check scripts. Maybe point 3 can be implemented. Does anyone remember in what thread was that asked?

**Comment by poeschlr** [comment]
About the scripting: I think the Forum user [HiGreg](https://forum.kicad.info/users/higreg/activity) asked about helping out with the scripting.
He also already implemented a DRC check script for silk/copper overlap so he should know how to implement something like this.

**Comment by antoniovazquezblanco** [comment]
About note 4:
imagen

-1.2+5.6 = 4.4

How did you calculate that?

**Comment by poeschlr** [comment]
I think your placement of the connector is correct.

From the measurements given in this part of the datasheet the "upper" egde of the connector can be calculated. (It should also equal the edge of the pads for the connector pins.)
screenshot from 2017-10-29 01-49-23

If you compare this with what i measured in freecad you will find that it is correct: (All other fab and copper features also seem to be correctly placed.) The only problem is that because this is a connector the courtyard offset should be 0.5mm not 0.25.
screenshot from 2017-10-29 01-59-46

**Comment by antoniovazquezblanco** [comment]
Done!

**Comment by evanshultz** [comment]
The scripting tools are located at https://github.com/pointhi/kicad-footprint-generator. I'll leave it up to you to take a look and ask any questions if you have them.

There are some silk-pad clearance checks implemented, but not for all pad types and all situations.

I calculated the body height as follows using the red numbers as the steps in my calculation above:
image
image

I calculate 5.7mm but that drawing shows 5.6mm. It bothers me that they don't match or that I'm not understanding how to make them match. Can you see why?

I took another look at the footprint and found a couple more things. Sorry for missing earlier:
1. There is no pin 1 mark on the fab layer.
1. Change `Pitch0.5mm` to `P0.5mm`. KLC3 will change the naming and while that's not the way most library parts are, and I didn't request that above, let's go with the newer naming now.

It's helpful if you can post a new image of a footprint if you make substantial changes.

**Comment by evanshultz** [comment]
I'd appreciate if someone can clarify the dimensional question above. The part drawing would seem conclusive, but the non-matching calculation bothers me.

Also, there are two more changes above which need to be made before merging. Thanks!

**Comment by poeschlr** [comment]
Here another sketch combining the information of your picture with the footprint (footprint in blue, your picture in white.)
Blue measurements are references because freecad does not allow over constraining sketches.
screenshot from 2017-11-01 17-28-27

This picture again shows that the footprint is done correctly. 

Edit:  **Assuming the mounting pin is centered on it's pad.**
Also the red line is the origin of kicad. The long whit line is the center of the mounting pin.
The x axis is just drawn such that it kind of looks nice. (not to scale in x, only y)

Another edit:
In your side view the reference point is somewhere in the middle of the connector. (It is the point where this connector connects to its counter part. Not anything related to the pins used to connect it to the PCB.)
Especially the thing you marked with 3 and 4 are not really usable. (3 references the internal connection point to the insert depth, 4 is the over all height when the connector is opened.) 

The picture posted by @antoniovazquezblanco   is better for finding the dimensions missing in the sketch that has your numbers 1 and 2 in it.

**Comment by evanshultz** [comment]
Thank you. The 1.4mm in your drawing above is 1.3mm in the datasheet (item 3 in the screenshot I posted above). That is the difference between 5.6mm and 5.7mm. I could be mis-reading the datasheet, and 0.1mm isn't much, but while the other 2 items I mentioned above being updated I'd like to resolve this small dimensional discrepancy.

**Comment by poeschlr** [comment]
The 1.3mm is not to the center of the mounting pad though. (It is to the internal connection point. They call it contact point in the drawing.)
My 1.4mm is the current position of the mounting pad in y.

**Comment by evanshultz** [comment]
Ah! OK. It looked like it was also the middle to me, but I get it now. Thank you.

That leaves just the F.Fab mark for pin 1 and changing `Pitch` to `P`.

**Comment by antoniovazquezblanco** [comment]
Sorry for not answering before. I have been away. I will fix both issues soon.

Thank you very much!

**Comment by antoniovazquezblanco** [comment]
imagen

Is this the standard way of marking pin 1 in FFab? Is there any other way that you prefer?

**Comment by evanshultz** [comment]
Thanks for the contribution. There are a few common pin 1 marking styles, and this one is good.

**Comment by antoniovazquezblanco** [comment]
Thank you! ;)

**Pull request merged**
