### PR TITLE
Create ZX62D-B-5PA8.kicad_mod

### PR DESCRIPTION
**Pull request by savenlid**
Mirco USB, right angle.
Best effort according to datasheet.
Not yet field-proven.

### CODE REVIEW

**Comment by pointhi** [comment]
please fix KLC

```
checking module: ZX62D-B-5PA8
  Violating Rule 10.2
    Doc property contains a full description of footprint.
  Violating Rule 10.5
    Attributes is set to the appropriate value, see tooltip for more information.
  Violating Rule 10.6
    All other properties are left to default values. (Move and Place: Free; Auto Place: 0 and 0,  Local
    Clearance Values: 0)
```

**Comment by evanshultz** [comment]
@savenlid Will you be able to review the comments above and address them soon?

**Comment by poeschlr** [comment]
USB connectors should go into the [Connectors_USB.pretty](https://github.com/KiCad/Connectors_USB.pretty) repo. I will close this PR for this reason. If @savenlid still wants to contribute, they will open a new pull request in the correct repo.

Now to the problems with this footprint:

The mounting pads toward the bottom have the wrong size. If i read the [datasheet](http://www.mouser.com/ds/2/185/ed_ZX_20140804-461411.pdf) (page 4) correctly it should be 1.5x0.65 drill size not 1.5x0.825

The value and reference should be moved closer to the part itself.

Now to the [KLC](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) violations (The new KLC is quite a bit different to the one that existed back in February last year.):
- Courtyard has a clearance of 0.5mm for connectors with respect to either pads or outline. (whichever is larger in the specific area/direction of the footprint.)
- The outline on fab should have a line width of 0.1mm
- The silk lines should have a width of 0.12mm and should be completely outside of the part. (The lower silk line is completely covered by the part if i understand it correctly.)
- A second reference on fab layer is missing

**Comment by poeschlr** [comment]
And some more points:
The 3d settings should be filled out: 
- Path: ${KISYS3DMOD}/library_name.3dshapes/footprint_name.wrl
- scale: 1,1,1
- offset: 0,0,0
- rotation: 0,0,0

The documentation field should contain a part description plus a link to the datasheet
The keyword field needs to be filled out.

**Comment by savenlid** [comment]
I fixed the error

Thanks for finding it.

I also connected the 3D model

updated hirose attached with 3d-models attached



tuned the fab layer to 0.1
moved some silk out from underneath the part.
added "1" marking on silk
clarified board-edge.


2017-06-22 10:31 GMT+02:00 Rene Pöschl <notifications@github.com>:

**Comment by poeschlr** [comment]
Remember to open a new pull request in the connectors usb repo for this footprint.
If you open the new PR please link back to this PR such that we know that these two pull requests are linked.

**Comment by savenlid** [comment]
i never use wrl

we have step for all 3d

we can do export step and get all models

unclear if that would ever work for wrl, but our mechanical dept use creo
as tool and deal with step as default.


2017-06-22 10:55 GMT+02:00 Nicholas Sävenlid <nicholas@savenlid.se>:

**Comment by poeschlr** [comment]
the path should end with .wrl
this is for compatibility with kicad stable (The 3d viewer of the stable release does not support step)

Our 3d model libs have the step and wrl file with the same file name in the same directory. this way one can use for example kicad stepup to work with step while enabeling the use of wrl files for the kicad internal 3d viewer.
(wrl allows for better material properties -> better looking renderings)

We do not force you do use step for your personal libs. But the official libs need to be compatible with kicad stable.

**Comment by poeschlr** [comment]
Correction:
We do not force you do use wrl for your personal libs. (you can use step for your personal libs is what i meant to write.)

**Comment by evanshultz** [comment]
@savenlid Will update this PR to conform to KLC? While it's perfectly fine for your personal libs to be designed however you like, all merged PRs must conform to the current KLC. If you're not going to submit parts that meet KLC, we'll be unable to merge this PR.

**Pull request closed without merging**
