### PR TITLE
Df13 dsa

### PR DESCRIPTION
**Pull request by SchrodingersGat**
I have re-generated the footprints for the DF13-xxx-125DSA connectors (vertical entry PTH connectors)

These are all passing KLC, and 3D models are available here:

https://github.com/KiCad/kicad-library/pull/249

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@ricardocrudo same again. Removed _PTH suffix, pass KLC

**Comment by pointhi** [comment]
- There is a point in the Part Number, which is missing in the footprint name
- please realign text and value fields, as done for other footprints
- fix script output, to have well formated files (you can also make a PR to my footprint-generator which gives 3d model support, and I fix the format bug for you)

the rest looks fine so far

**Comment by SchrodingersGat** [comment]
Ok, done this. I've also reset the 3D model properties as I'm working on better 3D models that don't require offsets and rotations

**Comment by pointhi** [comment]
thanks for your work

**Pull request merged**
