### PR TITLE
Hirose_DM3D-SF microSD card holder

### PR DESCRIPTION
**Pull request by evanshultz**
Fix of https://github.com/KiCad/Connectors_Hirose.pretty/pull/7.

Product page: https://www.hirose.com/product/en/download_file/key_name/DM3/category/Catalog/doc_file_id/49662/?file_category_id=4&item_id=195&is_series=1

Datasheet: https://media.digikey.com/PDF/Data%20Sheets/Hirose%20PDFs/DM3D-SF.pdf

microSD card width dimensions (11mm & 9.7mm) from https://cdn-shop.adafruit.com/datasheets/TS16GUSDHC6.pdf.

Image:
image

Changes from PR above:
- Set solder_mask_margin and solder_paste_margin to default.
- Add 3D model
- Fixed visibility, location, and size of footprint name on F.Fab.
- Fixed all F.Fab lines to be 0.1mm width.
- Set SMD attribute
- Placed ref des on F.Fab should be in the center of the footprint.
- Simplified zig zag lines on F.Fab to designate the keepout areas.
- Moved footprint origin to datasheet dimension origin.
- Correct courtyard placement to 0.5mm outside part body.
- Corrected pin 1-8 width to 0.7mm.
- Moved pin A Y location to ((10.7 - 9.15) / 2) + 9.15= 9.925mm.
- Simplified F.Fab lines to show only the part part body and microSD card.
- Updated silk to be placed outside the F.Fab box and avoid pads.

KLC violation is for origin, which I chose here since that's the origin of the footprint in the datasheet.

Question: The microSD card outline is, I believe, showing the absolute max dimensions during insertion or removal, which should be kept clear of other components. Is it best to put that on another layer? Dwgs.User, perhaps?

### CODE REVIEW

**Comment by evanshultz** [comment]
And a second question: I don't find any way to add a real keepout to a footprint. While this is a major limitation of the current footprint format, what can we do? Is there a better way than the hatched areas?

**Comment by evanshultz** [comment]
Corrected the footprint to work with an existing symbol:
image

**Comment by evanshultz** [comment]
@SchrodingersGat @jkriege2 @poeschlr 
Is anybody able to answer the question about footprint keepouts, and also review this? Thanks!

**Comment by SchrodingersGat** [comment]
@evanshultz you're right it is a major limitation of the library. (I'm currently working on a potential fix to this, but is a lot of work!)

For now I can only suggest manually drawing a keepout outline, perhaps on Drawings.User (this is what I have been suggesting on other PRs)

**Comment by poeschlr** [comment]
A recent example for the keepout workaround mentioned by oliver can be found in this pull request:
https://github.com/KiCad/RF_Modules.pretty/pull/13

**Comment by evanshultz** [comment]
Should this be rotated 180 degrees so pin 1 is closer to the top left? While that's a different orientation that the datasheet, it's closer to KLC. Though since this footprint doesn't have pin 1 on an outer corner, maybe it's no problem to allow it?

Also, I'll add [savenlid's other microSD footprint](https://github.com/KiCad/Connectors_Hirose.pretty/pull/8) and fix up the existing Hirose microSD card footprint all together in this PR. Review is helpful, but feel free to wait until they're all done here.

**Comment by evanshultz** [comment]
Adding fix of [#8](https://github.com/KiCad/Connectors_Hirose.pretty/pull/8) .

Product page: https://www.hirose.com/product/en/products/DM3/DM3BT-DSF-PEJS/

Datasheet: https://www.hirose.com/product/en/download_file/key_name/DM3BT-DSF-PEJS/category/Drawing%20(2D)/doc_file_id/44097/?file_category_id=6&item_id=06090029900&is_series=

Image:
image

Changes from PR #8 above:
- Set solder_mask_margin and solder_paste_margin to default.
- Add 3D model
- Fixed visibility, location, and size of footprint name on F.Fab.
- Fixed all F.Fab lines to be 0.1mm width and F.Silk lines to be 0.12mm.
- Set SMD attribute
- Placed ref des on F.Fab in the center of the footprint.
- Moved footprint origin to datasheet dimension origin.
- Updated the keepout area dimensions.
- Correct courtyard placement to 0.5mm outside part body.
- Updated silk to be placed outside the F.Fab box and avoid pads.
- Removed the lines on Eco.User layer.
- Updated the pin numbers to work with an existing symbol (see above).

KLC violation is for origin, which I chose here since that's the origin of the footprint in the datasheet. And it happens that this appears to be closest to placing pin 1 at the top left of the footprint as well.

Question: Same as above.

Next will be to review and update the existing one, microSD_Card_Receptacle_Hirose_DM3AT-SF-PEJM5.

**Comment by evanshultz** [comment]
I renamed the existing footprint from microSD_Card_Receptacle_Hirose_DM3AT-SF-PEJM5 to Hirose_DM3AT-SF-PEJM5. I then made just a couple changes:
- Added 3D model text.
- Added ref des on F.Fab.
- Moved silk ref des above the footprint.
- Moved and extended silk outlines to fit around part body as usual.
- Adjusted courtyard lines to 0.5mm distance (for a connector) on 0.1mm grid.
- Deleted text and line outside part body about keepout areas (the areas are still on Dwgs.User).

Product page: https://www.hirose.com/product/en/products/DM3/DM3AT-SF-PEJM5/

Datasheet: https://www.hirose.com/product/en/download_file/key_name/DM3AT-SF-PEJM5/category/Drawing%20(2D)/doc_file_id/44099/?file_category_id=6&item_id=06090031000&is_series=

Image:
image

Questions:
- This part looks so busy. Should it be simplified like the other ones above? Remove excess lines leaving just the extents of the part, use hatched areas for keepouts, and add the card extents for clearance?
- Should the origin stay here, even though it makes checking dimensions so much harder than if the original matches the datasheet location?

I verified the pinout will work with the symbol mentioned above. I didn't do a deep dive on pad locations and sizes and other things until the above questions are answered.

**Comment by evanshultz** [comment]
Looking at the above images, I noticed that on the first part (`DM3D-SF`) the counrtyard at the top of the image was too close to the pads. I pushed it back and also moved the ref des above the fab line.

**Comment by poeschlr** [comment]
I agree that the fab layer should be simplified. (Rule 7.4.ii.b)

**Comment by evanshultz** [comment]
@poeschlr @SchrodingersGat @jkriege2
Review requested!

Updated Hirose_DM3AT-SF-PEJM5 as mentioned above (in addition to verifying pad sizes, locations, etc.):
- Moved origin to the datasheet origin for easiest changes below.
- Dramatically simplified F.Fab.
- Added copper keepouts on F.Fab.
- Added F.Fab to show microSD card fully inserted and fully ejected positions.
- Corrected courtyard location.

Questions for all 3 footprints:
- The only KLC violation is for origin placement. On other weirdly-shaped parts I've had merged they weren't centered (also had the origin at the datasheet origin). Is this OK for these parts as well?
- Some of parts could be rotated so that pin 1 is closest to top left, but pin 1 isn't on the corner of any of these footprints. Are they OK as-is, without rotating.
- What layer is best for keepouts? I've seen F.Fab and you (Oliver) mentioned Dwgs.User, but it was a weak request. Does it matter right now since those areas are not constrained as keepouts?

The image in the post above has been updated.

**Comment by poeschlr** [comment]
Just a question: why do you work directly on the kicad repo instead of your own fork?

I will have a look at this PR tomorrow. (It's a bit late to do it today.)

**Comment by evanshultz** [comment]
I didn't know it would be an issue, since that's what a branch is for (development which is brought into trunk if all works out), but I won't do it anymore. I will always fork.

Thank you for reviewing!

**Comment by evanshultz** [comment]
@poeschlr Were you able to take a look at this PR?

**Comment by evanshultz** [comment]
@poeschlr Are you able to make the time to review this PR?

**Comment by evanshultz** [comment]
I've updated all footprints to use the new keepout style. Image:
image

@poeschlr Can you review? Should the SD card outline be on a different layer?

**Comment by evanshultz** [comment]
"KEEPOUT" text changed to Cmts.User layer. @poeschlr?

**Comment by evanshultz** [comment]
@poeschlr @hackscribble @jkriege2 @SchrodingersGat 
Is anyone able to review this PR? It's been languishing and I'd like to get it merged.

**Comment by SchrodingersGat** [comment]
Looks good, one final thought:

Given footprints for cards are scattered throughout different libraries, perhaps we should make a `Connectors_Card` repo? This corresponds to the overarching direction we are trying to move the libraries - to "sort by function"

**Comment by SchrodingersGat** [comment]
Ok, executive decision time. Please move this to the [Connectors_Card.pretty repo](https://github.com/KiCad/Connectors_Card.pretty

**Comment by evanshultz** [comment]
OK. Closing this case then. New PR raised at https://github.com/KiCad/Connectors_Card.pretty/pull/2.

**Pull request closed without merging**
