### PR TITLE
Added Hirose DF13-DS series (angled, PTH, 1.25mm)

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Passes all KLC
- Links to 3D models

3D models are here - https://github.com/KiCad/kicad-library/pull/249

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
These footprints have been generated with scripts available here:
https://github.com/SchrodingersGat/kicad-footprint-generator

**Comment by SchrodingersGat** [comment]
@ricardocrudo as with the JST fixes, I've tried to match the naming convention here. KLC all pass

**Comment by pointhi** [comment]
- There is a point in the Part Number, which is missing in the footprint name
- please realign text and value fields, as done for other footprints
- fix script output, to have well formated files (you can also make a PR to my footprint-generator which gives 3d model support, and I fix the format bug for you)

the rest looks fine so far

**Comment by SchrodingersGat** [comment]
@pointhi  fixed!

**Comment by pointhi** [comment]
thanks for your contribution

**Pull request merged**
