### PR TITLE
Create FX10A-168P-SV1.kicad_mod

### PR DESCRIPTION
**Pull request by savenlid**
made according to datasheet.
not taped out yet.

### CODE REVIEW

**Comment by pointhi** [comment]
Please fix KLC:

```
checking module: FX10A-168P-SV1
  Violating Rule 10.2
    Doc property contains a full description of footprint.
  Violating Rule 10.5
    Attributes is set to the appropriate value, see tooltip for more information.
  Violating Rule 10.6
    All other properties are left to default values. (Move and Place: Free; Auto Place: 0 and 0,  Local
    Clearance Values: 0)
```
- also note, the couryard has to have a clearance of 0.5mm for connectors

**Comment by evanshultz** [comment]
@savenlid Will you be able to review the comments above and address them soon?

**Comment by savenlid** [comment]
0.5mm hard court-yard limit just because its a connector makes no sense.

not speaking of this connector in particular but in general.

must be a case to case judgement.



2017-06-22 2:52 GMT+02:00 evanshultz <notifications@github.com>:

**Comment by evanshultz** [comment]
@savenlid Will update this PR to conform to KLC? While it's perfectly fine for your personal libs to be designed however you like, all merged PRs must conform to the current KLC. If you're not going to submit parts that meet KLC, we'll be unable to merge this PR.

**Comment by evanshultz** [comment]
@savenlid Please close this PR if you're not going to update it. Thank you.

**Comment by savenlid** [comment]
https://github.com/savenlid/kicad

**Pull request closed without merging**
