### PR TITLE
U.FL-R-SMT-1 connector

### PR DESCRIPTION
**Pull request by jeromebeguin**

### CODE REVIEW

**Comment by jeromebeguin** [comment]
U.FL connector
I don't have 3D model for this part sorry. 

image
image

**Comment by poeschlr** [comment]
Sorry for the late review.

Could you add the prefix Hirose_ to the footprint name to be consistent with the rest of the library?
It would also be a good idea to add a link to the datasheet (or in this case the catalog) in the documentation field (https://www.hirose.com/product/en/download_file/key_name/U.FL/category/Catalog/doc_file_id/31697/?file_category_id=4&item_id=15&is_series=1)

@SchrodingersGat or @jkriege2 this footprint should have an are where no conductive traces should be. How should something like that be communicated with the user? (should there be a marking on some layer or is it the responsibility of each user to read the datasheet? If there should be a marking. Which layer would be the best option?)

**Comment by jeromebeguin** [comment]
Actually it would be very good to have in future version of Kicad for each copper layer an extra layer which is a no trace layer. Also for each face having a kind of keep out layer which tell you where not to put component could be very useful.

**Comment by poeschlr** [comment]
I agree but we need to work with what we currently have.
I think there was another footprint that simply put a rectangle on the user drawings layer and a warning text on the comments layer.

This way the user can then place a keepout area over this rectangle.

**Comment by evanshultz** [comment]
@jeromebeguin  Will you be able to review the comments above and address them soon? The only known change I see is the re-naming of the footprint, but please also confirm the link to the footprint posted by @poeschlr.

@SchrodingersGat @jkriege2 Is there a way to create Cu (trace, via, zone, etc.) keepouts on a footprint? If there's not a correct way that's picked up by the design rules, how to best indicate this?

**Pull request closed without merging**
