### PR TITLE
added 3D model references and added ${KISYS3DMOD}

### PR DESCRIPTION
**Pull request by Shackmeister**
Not gonna fix more on this for now, please merge as is

### CODE REVIEW

**Comment by poeschlr** [comment]
Could you leave microSD_Card_Receptacle_Hirose_DM3AT-SF-PEJM5 unchange such that @evanshultz does not need to merge in pull request #17?

**Comment by Shackmeister** [comment]
@poeschlr done

**Comment by evanshultz** [comment]
Thank you!

**Comment by poeschlr** [comment]
Thanks.

**Pull request merged**
