### PR TITLE
adding DM3AT micro SD card footprint

### PR DESCRIPTION
**Pull request by jeromebeguin**
This is the only directory I found logical to put this footprint.

### CODE REVIEW

**Comment by jkriege2** [comment]
Very nice work!

a few questions:
1) Why did you put something on Eco1-layer?
2) set placement-type/attribut to SMT and add descrption/keywords:
2017-01-20 22_57_00-footprint editor no active library
3) set linewidth of courtyard to 0.05mm

Best,
JAN

**Comment by jeromebeguin** [comment]
Thank you. 

1. On the Eco1-layer is the keep out zone. It seems there is no keepout layer available so to fully describe the component, I used the ECO-1. Actually it would be very nice to have such layers with error check for the routing. 

2. Funny thing I don't have the placement type option on my footprint properties. Where could I find them ?

3. I gonna do this. Is it possible to change the size of an entire group of line at the same time ?

**Comment by jkriege2** [comment]
ad 2) I think in the stable versions its still called differently but should be at the same place (observe the tooltips!)
a 3) best do it with a textedito directly in the file

**Comment by jkriege2** [comment]
Please fix the footprint with the `--fix`-option of our checklib-scripts. This should move the anchor as required and move the Courtyard onto a 0.01mm grid.

Maybe add a text `keepout` to the ECO1-layer, or cross the keepouts out, so one has a grasp of what that means ;-)

Best,
JAN

**Comment by jkriege2** [comment]
Looks good!

I checked for other footprints haveing a "keepout" ... and found 1: `RF_Modules:CYBLE-21pin-10x10mm` There they used `Dwgs.User` to sketch the keepout and `Cmts.User` for commenting text:
2017-01-25 20_58_32-footprint editor no active library

Maybe use the same layers here?

best,
JAN

**Comment by jkriege2** [comment]
Also: Please ensure that the pin-numbers on your footprint match the symbol in `conn.lib`that we already have: 
2017-01-25 21_08_22-part library editor d__kicad_kicad-library-review_library_conn lib
see also: http://elasticsheep.com/wp-content/uploads/2010/01/sd-card-pinout.png

This would mean for your footprint rotating pin9 to the right. make sure the sielding pins are 12 and 13 and that you connect the card-detect correctly ...

Best,
JAN

**Comment by jkriege2** [comment]
I think the pin-numbering should be like this:
2017-01-26 22_11_32-footprint editor no active library

**Comment by jeromebeguin** [comment]
The Pinout is correct: [DM3AT](http://www.mouser.com/ds/2/185/DM3_catalog-939223.pdf).

**Comment by jkriege2** [comment]
No it's not ... observe that DAT2 is pin1 in the datasheet, but pin9 in the Symbol ... or am I mistaken?

cu
JAN

**Comment by jeromebeguin** [comment]
Yeah, no. You are not looking the right symbol. Check the Micro_SD_Card symbol. It's the right pinout. I have made another symbol (coming soon) with the det A & B pins.

**Comment by jkriege2** [comment]
sorry my error ;-) thought it's an SD-Card ...

**Comment by jkriege2** [comment]
One last remark: There is already a SD-card receptable `SD_Card_Receptacle` in `Connector.pretty` what about renaming this component to `microSD_Card_Receptacle_Hirose_DM3AT-SF-PEJM5`

best,
JAN

**Comment by jkriege2** [comment]
OK! Thanks for all the work!

JAN

**Pull request merged**
